// Two-player browser scenario: a real browser client + a bot. Verifies remote players, chat bubbles, thrown props, signs, planks.
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright-core';
import { Bot, sleep } from './bot.js';

const PORT = 8700 + Math.floor(Math.random() * 200);
fs.rmSync('.scratch/scn-data', { recursive: true, force: true });
const OUT = path.resolve('.scratch/shots'); fs.mkdirSync(OUT, { recursive: true });
const proc = spawn('node', ['server/index.js'], { env: { ...process.env, DEV: '1', PORT, DATA_DIR: '.scratch/scn-data', PACE: 'fast' }, stdio: ['ignore', 'pipe', 'pipe'] });
proc.stdout.on('data', (d) => { if (process.env.DEBUG_GRAB) process.stdout.write(d); });
proc.stderr.on('data', (d) => console.log('[server err]', d.toString().trim()));
await new Promise((res) => proc.stdout.on('data', (d) => { if (d.toString().includes('is up')) res(); }));
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist', '--no-sandbox', '--autoplay-policy=no-user-gesture-required'] });
const page = await (await browser.newContext({ viewport: { width: 1100, height: 620 } })).newPage();
const logs = [];
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') logs.push(`[${m.type()}] ${m.text()}`); });
page.on('pageerror', (e) => logs.push('[pageerror] ' + e.message));
await page.goto(`http://localhost:${PORT}/?name=Viewer`);
await page.selectOption('#pquality', 'low');
await page.waitForFunction(() => !document.getElementById('enter').disabled);
await page.click('#enter');
await page.waitForFunction(() => window.__game && window.__game.ready, null, { timeout: 120000 });
await page.waitForSelector('#dg-ok', { state: 'attached', timeout: 60000 });
await page.evaluate(() => { const G = __game; document.getElementById('dg-ok')?.click(); document.getElementById('digest').hidden = true; G.starting = false; G.local.locked = true; G.forceTod = 15; });
const me = await page.evaluate(() => ({ x: __game.local.pos.x, z: __game.local.pos.z }));
console.log('browser player at', me);
const bot = new Bot(`ws://localhost:${PORT}/ws`, 'Wanderer', { streamer: true });
await bot.connect();
await page.evaluate(() => { const G = __game, L = G.local; L.teleport(104, G.terrain.height(104, 60), 60, 'surface', -1.57); L.yaw = -1.57; L.pitch = 0.0; });
await bot.walkTo(96, 58, 9, 30000);
await sleep(600);
bot.send({ t: 'act', a: 'chat', text: 'the lake is glowing, did you see?' });
bot.send({ t: 'act', a: 'emote', e: 0 });
await page.waitForTimeout(2500);
await page.screenshot({ path: OUT + '/scn_remote.png' });
// browser player grabs a crate and throws it (uses the real client code path)
const crate = [...bot.props.values()].filter((p) => p.ty === 'crate').sort((a, b) => Math.hypot(a.pose[0] - 112, a.pose[2] - 57) - Math.hypot(b.pose[0] - 112, b.pose[2] - 57))[0];
await page.evaluate((c) => { const G = __game, L = G.local; L.teleport(c.pose[0] + 2.2, G.terrain.height(c.pose[0] + 2.2, c.pose[2]), c.pose[2], 'surface', -1.57); L.yaw = -1.57; L.pitch = -0.5; L.updateCamera(0.02, G.env); L.sendAcc = 1; L.updateNet(0, false); }, crate);
await page.waitForTimeout(1200);
console.log('crate', crate.pose.slice(0,3), 'player', await page.evaluate(() => { const L = __game.local; const a = L.aim(); return JSON.stringify({ starting: __game.starting, locked: L.locked, frozen: L.frozen, camdir: (() => { const d = new (L.camera.position.constructor)(); L.camera.getWorldDirection(d); return d; })(), pos: L.pos, o: a.o, d: a.d, tool: L.tool, pitch: L.pitch, yaw: L.yaw }); }));
await page.evaluate(() => { const L = __game.local; L.tool = 0; L.primaryDown(); });
await page.waitForTimeout(1500);
const held = await page.evaluate(() => __game.local.heldId);
console.log('held prop:', held);
await page.evaluate(() => { const L = __game.local; L.chargeT = 0.8; L.charging = true; L.pitch = 0.25; L.updateCamera(0.02, __game.env); L.primaryUp(); });
await page.waitForTimeout(1800);
await page.screenshot({ path: OUT + '/scn_throw.png' });
// place a plank + sign
await page.evaluate(() => { const L = __game.local; L.pitch = -0.35; L.updateCamera(0.02, __game.env); L.setTool(2); L.primaryDown(); });
await page.waitForTimeout(800);
await page.evaluate(() => { const L = __game.local; L.yaw += 0.8; L.updateCamera(0.02, __game.env); L.setTool(2); L.primaryDown(); });
await page.waitForTimeout(800);
bot.send({ t: 'act', a: 'sign', ...bot.aimAt(bot.pos.x + 2, bot.pos.y, bot.pos.z + 2), text: 'PIET WAS HERE' });
await page.waitForTimeout(1500);
await page.evaluate(() => { const L = __game.local; L.yaw = -1.0; L.pitch = 0.05; L.setTool(0); L.updateCamera(0.02, __game.env); });
await page.waitForTimeout(2500);
await page.screenshot({ path: OUT + '/scn_build.png' });
const stats = await page.evaluate(() => { const i = __game.renderer.info; return { calls: i.render.calls, tris: i.render.triangles, geos: i.memory.geometries, tex: i.memory.textures, planks: __game.objects.planks.size, signs: __game.objects.signs.size, players: __game.entities.players.size, props: __game.objects.props.size }; });
console.log('render info', stats);
console.log(logs.length ? 'LOGS:\n' + [...new Set(logs)].join('\n') : 'no console errors');
bot.close(); await browser.close(); proc.kill(); process.exit(0);
