import { spawn } from 'node:child_process';
import fs from 'node:fs';
import { chromium } from 'playwright-core';
import { Bot, sleep } from './bot.js';
const PORT = 8900 + Math.floor(Math.random() * 90);
fs.rmSync('.scratch/vw-data', { recursive: true, force: true });
const proc = spawn('node', ['server/index.js'], { env: { ...process.env, PORT, DATA_DIR: '.scratch/vw-data', PACE: 'fast' }, stdio: ['ignore', 'pipe', 'pipe'] });
await new Promise((res) => proc.stdout.on('data', (d) => { if (d.toString().includes('is up')) res(); }));
const s = new Bot(`ws://localhost:${PORT}/ws`, 'StreamerX', { streamer: true }); await s.connect();
const st = await s.waitFor('stream'); console.log('code', st.code);
const b = new Bot(`ws://localhost:${PORT}/ws`, 'Other'); await b.connect();
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const page = await (await browser.newContext({ viewport: { width: 1100, height: 900 } })).newPage();
const logs = []; page.on('console', (m) => { if (m.type() === 'error') logs.push(m.text()); }); page.on('pageerror', (e) => logs.push('pageerror ' + e.message));
await page.goto(`http://localhost:${PORT}/viewer?code=${st.code}`);
await page.fill('#vname', 'ChatGuy'); await page.click('#jf button');
await page.waitForSelector('#console:not([hidden])');
await page.waitForTimeout(6000);
await page.click('.fxb[data-k="gust"]:not([disabled])');
await page.waitForTimeout(800);
const chron = await b.waitFor('chron', (m) => m.e.kind === 'viewers', 6000);
console.log('other player saw:', chron.e.title, '|', chron.e.text);
await page.screenshot({ path: '.scratch/shots/viewer.png' });
console.log(logs.length ? logs.join('\n') : 'no console errors');
await browser.close(); s.close(); b.close(); proc.kill(); process.exit(0);
